### PR TITLE
Software-766 Refactoring LiveFeeder

### PR DESCRIPTION
**Pull request by dtrailin**

### CODE REVIEW

**Comment by pcernek** [comment]
Nice! Have you tested any of this?

**Comment by dtrailin** [comment]
I builds and runs. I don't have a lepton so I can't tell you if it works or not.

**Comment by pcernek** [comment]
Fair enough. I pushed a FileSystemImageStream to SOFTWARE-802-enclosureComms, which should be all you need for testing. (Sorry about the conflict.)

Wait until I push that to dev, and maybe rebase your branch on top of it to use it to run a test.

**Comment by dtrailin** [comment]
The code is now a point where it is now in a mergable state. I'd nice to get a CR @pcernek .

**Comment by pcernek** [comment]
Beauty! I'll take a look tomorrow afternoon.

**Pull request merged**
